--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: gateway-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: gateway
    spec: 
      containers: 
        - 
          env: 
            - 
              name: WSO2_CLOUD_ORG_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: WSO2_CLOUD_ORG_KEY
            - 
              name: WSO2_CLOUD_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: WSO2_CLOUD_EMAIL
- 
              name: WSO2_CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: WSO2_CLOUD_PASSWORD
image: "docker.cloud.wso2,com/onprem-gateway:2.5.0"
          imagePullPolicy: Always
          name: gateway
          ports: 
            - 
              containerPort: 80
